services:
  stay-ease-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Exposing to port 8080 of the local machine
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      # Set environment variables for MySQL (adjust as needed)
      SPRING_DATASOURCE_URL:  jdbc:mysql://host.docker.internal:3306/hotel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sql_pass